### ISSUE TITLE
[Bug] Feature list missing copy/open in growthbook function

### ISSUE THREAD

**Issue by daxaxelrod** [growthbook/growthbook-vsce#5]
### Summary

List of features doesn't have hover menu

#### Expected Behavior

Expect list of features to have copy/edit when hovering a row

#### Current Behavior

retrieves list of features correctly, onHover does nothing

**Comment by tinahollygb** [comment]
This bug is fixed in 0.0.3. Please allow some time for the published extension to propagate to VSCode clients. Thanks again for your report.
